DO
$$
BEGIN
	IF NOT EXISTS (
SELECT FROM pg_catalog.pg_roles WHERE rolname='example_user'
) THEN
CREATE ROLE example_user WITH SUPERUSER CREATEDB CREATEROLE LOGIN ENCRYPTED PASSWORD '123456';
END IF;
END
$$;